### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [brainvisa/morphologist#14]

**Comment by DimitriPapadopoulos** [comment]
CeCILL-B?

**Comment by DimitriPapadopoulos** [comment]
Seems so, according to https://github.com/brainvisa/morphologist/blob/0ea131d3847acc732e93a9ef495f4bf5c0b1c44c/morphologist/info.py#L52.

**Comment by denisri** [comment]
Hm, Morphologist-UI is using PyQt thus is probably bound to GPL/CeCILL-v3, so I guess there is a mistake there...

**Comment by DimitriPapadopoulos** [comment]
Will change to CeCILL then.

**Comment by DimitriPapadopoulos** [comment]
It's probably [CeCILL v2.1](https://cecill.info/licences/Licence_CeCILL_V2.1-en.html), there's no CeCILL v3.

**Comment by denisri** [comment]
Yes it's v2.1, that's true. I'm a bit tired ;)
